apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name:  {{ .Values.appbase.name }} 
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  name: {{ .Values.appbase.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appbase.name }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.appbase.name }}
    spec:
      containers:
        - env:
        {{- $equ := ""}}
        {{- $at := ""}}
        {{- if and .Values.elasticsearch.username .Values.elasticsearch.password}}
        {{- $equ = ":"}}
        {{- $at = "@"}}
        {{- end }}
            - name: USERNAME
              value: {{ .Values.appbase.username }}
            - name: PASSWORD
              value: {{ .Values.appbase.password }}
            - name: APPBASE_ID
              value: {{ .Values.appbase.id }}
            - name: ES_CLUSTER_URL
            {{- if and (eq .Values.elasticsearch.scheme "http") (empty .Values.elasticsearch.port)}}
              value: {{ .Values.elasticsearch.scheme }}://{{ .Values.elasticsearch.username }}{{ $equ }}{{ .Values.elasticsearch.password }}{{$at}}{{ .Values.elasticsearch.host}}:80
              {{- else if and (eq .Values.elasticsearch.scheme "https") (empty .Values.elasticsearch.port)}}
              value: {{ .Values.elasticsearch.scheme }}://{{ .Values.elasticsearch.username }}{{ $equ }}{{ .Values.elasticsearch.password }}{{$at}}{{ .Values.elasticsearch.host}}:443
              {{- else if and (empty .Values.elasticsearch.schem) (.Values.elasticsearch.port)}}
              value: {{ .Values.elasticsearch.scheme | default "http"}}://{{ .Values.elasticsearch.username }}{{ $equ }}{{ .Values.elasticsearch.password }}{{$at}}{{ .Values.elasticsearch.host}}:{{ .Values.elasticsearch.port}}
              {{- else if and (.Values.elasticsearch.schem) (.Values.elasticsearch.port)}}
              value: {{ .Values.elasticsearch.scheme | default "http"}}://{{ .Values.elasticsearch.username }}{{ $equ }}{{ .Values.elasticsearch.password }}{{$at}}{{ .Values.elasticsearch.host}}:{{ .Values.elasticsearch.port}}
              {{- else }}
              value: {{ .Values.elasticsearch.scheme | default "http"}}://{{ .Values.elasticsearch.username }}{{ $equ }}{{ .Values.elasticsearch.password }}{{$at}}{{ .Values.elasticsearch.host}}:{{ .Values.elasticsearch.port | default 9200}}
              {{- end }}
            - name: LOG_FILE_PATH
              value: "/var/log/es.json"
          image: {{.Values.appbase.image}}:{{.Values.appbase.tag | default .Chart.AppVersion}}
          imagePullPolicy: IfNotPresent
          name: {{ .Values.appbase.name }}
          ports:
            - containerPort: {{ .Values.appbase.port }}
              name: http
              protocol: TCP
          volumeMounts:
            - name: varlog
              mountPath: /var/log
              subPath: es.json
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers

  replicas: {{ .Values.appbase.nodes }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appbase.name }}
  labels:
    app: {{ .Values.appbase.name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.appbase.port }}
      targetPort: {{ .Values.appbase.port }}
  selector:
    app: {{ .Values.appbase.name }}