{{ if eq .Values.loadBalancer.serviceType "NodePort" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appbase.name }}-nodeport
spec:
  type: NodePort
  selector:
    app: {{ .Values.appbase.name }}
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 80
      targetPort: 8000
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30077
{{ end }}